version: '3'

services:
  presence:
    image: salvq/presence:2.3.0
    container_name: presence
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      - HOST=192.168.1.106
      - PORT=1883
      - USER=data
      - PASSWORD=qwer14
      - LOCATION=jakubroom
      - LOGGING=DEBUG
      - DBASE=http://192.168.1.106:8019/presence/database.json
    volumes:
      - /etc/localtime:/etc/localtime:ro
